import type { Constants } from "../types/gameTypes.js";

/**
 * Game configuration constants
 * Contains all the core game balance values and settings
 */
export const CONSTANTS: Constants = {
  MERIDIAN_COUNT: 12,
  BASE_AGE: 18,
  BASE_QI_PURITY: 100,
  MERIDIAN_DIFFICULTY_BASE: 200,
  QI_FOLD_THRESHOLD: 100,
  QI_FOLD_MULTIPLIER: 2,
  QI_PURITY_BONUS: 2,
  CIRCULATION_BASE_DIFFICULTY: 10,
  CIRCULATION_DIFFICULTY_MULTIPLIER: 6,
  GAME_TICK_INTERVAL: 1000,
  LUCKY_ENCOUNTER_BASE_CHANCE: 0.05,
  LUCKY_ENCOUNTER_TRIGGER: 0.1,
  QI_PURITY_DEGRADATION_BASE: 0.96,
  LOG_MAX_LENGTH: 1000,
  PILLAR_QI_COST: 400,
};
